#!/usr/bin/env python

# Prints a formatted short reference for a given PHP function.
# Usage: php-short-reference <function>

import os
import re
import sys

def formatted_reference(fname):
    _, output = os.popen2(['php', '--rf', fname])
    reference = output.read()
    
    if reference.startswith('Exception:'): sys.exit(1)
    
    params = re.findall(r'Parameter #[0-9]+ \[ <([^>]+)> ([^ ]+) \]', reference)
    required = [param for necessity, param in params if necessity == 'required']
    optional = [param for necessity, param in params if necessity == 'optional']
    
    required_params = ', '.join(required)
    optional_params = reduce(lambda a, b: a + ' [, %s' % b,
                             (p if p != '$...' else '...' for p in optional),
                             '') + ']' * len(optional)
    
    return '%s( %s%s )' % (fname, required_params, optional_params)

if __name__ == '__main__':
   print formatted_reference(sys.argv[1])
