#!/usr/bin/env python

# Prints a Markdown-formatted version of the online PHP reference
# documentation.
#
# Usage: php-reference <function>

import bs4
import html2text
import re
import sys
import urllib2

def reference_html(php_symbol):
    """
    Fetches reference HTML for a PHP built-in. The documentation is loaded
    from http://php.net.
    """
    url = 'http://php.net/%s' % php_symbol
    return urllib2.urlopen(url).read()

def normalised_html(html):
    """
    Extracts (and transforms) relevant parts of an HTML string.
    """
    soup = bs4.BeautifulSoup(html)
    root = soup.find(attrs='refentry')
    
    # Format function signature
    synopsis = root.find(attrs='methodsynopsis')
    pre = soup.new_tag('pre')
    pre.append(re.sub('\s+', ' ', synopsis.get_text().strip()))
    synopsis.replace_with(pre)
    
    # Remove unwanted information
    changelog = root.find(attrs='changelog')
    if changelog: changelog.decompose()

    # Remove misused/unnecessary <blockquote>s
    for tag in root.find_all('blockquote'):
        tag.unwrap()
        
    # Convert <h3> => <h2>
    for h3 in root.find_all('h3'):
        h2 = soup.new_tag('h2')
        h2.append(h3.get_text().strip())
        h3.replace_with(h2)
        
    # Unwrap decorated <code> elements. Markdown looks a bit noisy when
    # different formatting elements are combined (e.g. **`foo`**)
    for code in root.find_all('code'):
        if code.parent.name in ('em', 'strong'):
            code.parent.unwrap()
            
    # Convert block <code> => <pre>
    for code in [div.find('code') for div in root.find_all('div', 'phpcode')]:
        for br in code.find_all('br'):
            br.replace_with('\n')
        pre = soup.new_tag('pre')
        pre.append(code.get_text().strip())
        code.replace_with(pre)

    return unicode(root)

def formatted_reference(html):
    """
    Converts an HTML string to Markdown.
    """
    converter = html2text.HTML2Text()
    converter.ignore_links = True
    converter.body_width = 0

    text = converter.handle(html)
    text = re.sub(' +$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\n\n+', '\n\n', text, flags=re.MULTILINE)
    return text

if __name__ == '__main__':
    print formatted_reference(normalised_html(reference_html(sys.argv[1])))
